In [8]:
from pathlib import Path
import sys
import pandas as pd
import fastparquet

In [9]:
PROJECT_ROOT = Path.cwd().parent

sys.path.append(str(PROJECT_ROOT))

In [10]:
dim_items = pd.read_parquet(f"{PROJECT_ROOT}/data/processed/movies/dim_items.parquet", engine="fastparquet")
item_genres = pd.read_parquet(f"{PROJECT_ROOT}/data/processed/movies/item_genres.parquet", engine="fastparquet")

In [16]:
from src.recommenders.popularity import (
    get_top_movies,
    get_top_movies_by_genre,
    get_available_genres
)

In [13]:
get_top_movies(
    dim_items,
    top_n=20
)[
    [
        "title",
        "vote_average",
        "vote_count",
        "weighted_rating"
    ]
]

,title,vote_average,vote_count,weighted_rating
314,The Shawshank Redemption,8.5,8358.0,8.445871
834,The Godfather,8.5,6024.0,8.425442
10306,Dilwale Dulhania Le Jayenge,9.1,661.0,8.421477
12477,The Dark Knight,8.3,12269.0,8.265479
2842,Fight Club,8.3,9678.0,8.256387
292,Pulp Fiction,8.3,8670.0,8.251408
522,Schindler's List,8.3,4436.0,8.206643
23655,Whiplash,8.3,4376.0,8.205408
5480,Spirited Away,8.3,3968.0,8.196059
2210,Life Is Beautiful,8.3,3643.0,8.187177
1178,The Godfather: Part II,8.3,3418.0,8.180082
1152,One Flew Over the Cuckoo's Nest,8.3,3001.0,8.164262
351,Forrest Gump,8.2,8147.0,8.150275
1154,The Empire Strikes Back,8.2,5998.0,8.132922
1176,Psycho,8.3,2405.0,8.132722
18457,The Intouchables,8.2,5410.0,8.125841
40219,Your Name.,8.5,1030.0,8.112548
289,Leon: The Professional,8.2,4293.0,8.107238
3029,The Green Mile,8.2,4166.0,8.104515
1170,GoodFellas,8.2,3211.0,8.077464

In [14]:
get_top_movies_by_genre(
    dim_items,
    item_genres,
    genre="Action",
    top_n=20
)[
    [
        "title",
        "vote_average",
        "vote_count",
        "weighted_rating"
    ]
]

,title,vote_average,vote_count,weighted_rating
12477,The Dark Knight,8.3,12269.0,8.195280
15474,Inception,8.1,14075.0,8.015020
1154,The Empire Strikes Back,8.2,5998.0,8.001680
6999,The Lord of the Rings: The Return of the King,8.1,8226.0,7.958008
256,Star Wars,8.1,6778.0,7.929727
4862,The Lord of the Rings: The Fellowship of the Ring,8.0,8892.0,7.873330
5813,The Lord of the Rings: The Two Towers,8.0,7641.0,7.853846
23735,Guardians of the Galaxy,7.9,10014.0,7.791542
2457,The Matrix,7.9,9079.0,7.780947
13600,Inglourious Basterds,7.9,6598.0,7.739289
3455,Gladiator,7.9,5566.0,7.711912
1167,Return of the Jedi,7.9,4763.0,7.683172
1171,Alien,7.9,4564.0,7.674638
4134,Scarface,8.0,3017.0,7.661263
24437,Big Hero 6,7.8,6289.0,7.639224
9427,Oldboy,8.0,2000.0,7.523033
6724,Kill Bill: Vol. 1,7.7,5091.0,7.513541
18244,The Dark Knight Rises,7.6,9263.0,7.498329
10836,V for Vendetta,7.7,4562.0,7.494025
582,Terminator 2: Judgment Day,7.7,4274.0,7.481579

In [17]:
get_top_movies(dim_items)

,item_id,source_item_id,title,description,release_date,runtime,language,popularity,vote_average,vote_count,belongs_to_collection,production_companies,production_countries,budget,revenue,poster_path,domain,weighted_rating
314,315,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,1994-09-23,142.0,en,51.645403,8.5,8358.0,<NA>,"[{'name': 'Castle Rock Entertainment', 'id': 9...","[{'iso_3166_1': 'US', 'name': 'United States o...",25000000,2.834147e+07,/9O7gLzmreU0nGkIB6K3BsJbzvNv.jpg,movie,8.445871
834,835,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,175.0,en,41.109264,8.5,6024.0,"{'id': 230, 'name': 'The Godfather Collection'...","[{'name': 'Paramount Pictures', 'id': 4}, {'na...","[{'iso_3166_1': 'US', 'name': 'United States o...",6000000,2.450664e+08,/rPdtLWNsZmAtoZl9PK7S2wE3qiS.jpg,movie,8.425442
10306,10307,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-20,190.0,hi,34.457024,9.1,661.0,<NA>,"[{'name': 'Yash Raj Films', 'id': 1569}]","[{'iso_3166_1': 'IN', 'name': 'India'}]",13200000,1.000000e+08,/2gvbZMtV1Zsl7FedJa5ysbpBx2G.jpg,movie,8.421477
12477,12478,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,2008-07-16,152.0,en,123.167259,8.3,12269.0,"{'id': 263, 'name': 'The Dark Knight Collectio...","[{'name': 'DC Comics', 'id': 429}, {'name': 'L...","[{'iso_3166_1': 'GB', 'name': 'United Kingdom'...",185000000,1.004558e+09,/1hRoyzDtpgMU7Dz4JF22RANzQO7.jpg,movie,8.265479
2842,2843,550,Fight Club,A ticking-time-bomb insomniac and a slippery s...,1999-10-15,139.0,en,63.869599,8.3,9678.0,<NA>,[{'name': 'Twentieth Century Fox Film Corporat...,"[{'iso_3166_1': 'DE', 'name': 'Germany'}, {'is...",63000000,1.008538e+08,/adw6Lq9FiC9zjYEpOqfq03ituwp.jpg,movie,8.256387
292,293,680,Pulp Fiction,"A burger-loving hit man, his philosophical par...",1994-09-10,154.0,en,140.950236,8.3,8670.0,<NA>,"[{'name': 'Miramax Films', 'id': 14}, {'name':...","[{'iso_3166_1': 'US', 'name': 'United States o...",8000000,2.139288e+08,/dM2w364MScsjFf8pfMbaWUcWrR.jpg,movie,8.251408
522,523,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-11-29,195.0,en,41.725123,8.3,4436.0,<NA>,"[{'name': 'Universal Pictures', 'id': 33}, {'n...","[{'iso_3166_1': 'US', 'name': 'United States o...",22000000,3.213656e+08,/yPisjyLweCl1tbgwgtzBCNCBle.jpg,movie,8.206643
23655,23656,244786,Whiplash,"Under the direction of a ruthless instructor, ...",2014-10-10,105.0,en,64.299990,8.3,4376.0,<NA>,"[{'name': 'Bold Films', 'id': 2266}, {'name': ...","[{'iso_3166_1': 'US', 'name': 'United States o...",3300000,1.309200e+07,/lIv1QinFqz4dlp5U4lQ6HaiskOZ.jpg,movie,8.205408
5480,5481,129,Spirited Away,A ten year old girl who wanders away from her ...,2001-07-20,125.0,ja,41.048867,8.3,3968.0,<NA>,"[{'name': 'Studio Ghibli', 'id': 10342}]","[{'iso_3166_1': 'JP', 'name': 'Japan'}]",15000000,2.749251e+08,/ynXoOxmDHNQ4UAy0oU6avW71HVW.jpg,movie,8.196059
2210,2211,637,Life Is Beautiful,A touching story of an Italian book seller of ...,1997-12-20,116.0,it,39.394970,8.3,3643.0,<NA>,"[{'name': 'Miramax Films', 'id': 14}, {'name':...","[{'iso_3166_1': 'IT', 'name': 'Italy'}]",20000000,2.294000e+08,/f7DImXDebOs148U4uPjI61iDvaK.jpg,movie,8.187177
1178,1179,240,The Godfather: Part II,In the continuing saga of the Corleone crime f...,1974-12-20,200.0,en,36.629307,8.3,3418.0,"{'id': 230, 'name': 'The Godfather Collection'...","[{'name': 'Paramount Pictures', 'id': 4}, {'na...","[{'iso_3166_1': 'US', 'name': 'United States o...",13000000,4.754284e+07,/bVq65huQ8vHDd1a4Z37QtuyEvpA.jpg,movie,8.180082
1152,1153,510,One Flew Over the Cuckoo's Nest,While serving time for insanity at a state men...,1975-11-18,133.0,en,35.529554,8.3,3001.0,<NA>,"[{'name': 'United Artists', 'id': 60}, {'name'...","[{'iso_3166_1': 'US', 'name': 'United States o...",3000000,1.089813e+08,/2Sns5oMb356JNdBHgBETjIpRYy9.jpg,movie,8.164262
351,352,13,Forrest Gump,A man with a low IQ has accomplished great thi...,1994-07-06,142.0,en,48.307194,8.2,8147.0,<NA>,"[{'name': 'Paramount Pictures', 'id': 4}]","[{'iso_3166_1': 'US', 'name': 'United States o...",55000000,6.779454e+08,/yE5d3BUhE8hCnkMUJOo1QDoOGNz.jpg,movie,8.150275
1154,1155,1891,The Empire Strikes Back,"The epic saga continues as Luke Skywalker, in ...",1980-05-17,124.0,en,19.470959,8.2,5998.0,"{'id': 10, 'name': 'Star Wars Collection', 'po...","[{'name': 'Lucasfilm', 'id': 1}, {'name': 'Twe...","[{'iso_3166_1': 'US', 'name': 'United States o...",18000000,5.384000e+08,/6u1fYtxG5eqjhtCPDx04pJphQRW.jpg,movie,8.132922
1176,1177,539,Psycho,When larcenous real estate clerk Marion Crane ...,1960-06-16,109.0,en,36.826309,8.3,2405.0,"{'id': 119674, 'name': 'Psycho Collection', 'p...","[{'name': 'Paramount Pictures', 'id': 4}, {'na...","[{'iso_3166_1': 'US', 'name': 'United States o...",806948,3.200000e+07,/81d8oyEFgj7FlxJqSDXWr8JH8kV.jpg,movie,8.132722
18457,18458,77338,The Intouchables,A true story of two men who should never have ...,2011-11-02,112.0,fr,16.086919,8.2,5410.0,<NA>,"[{'name': 'Gaumont', 'id': 9}, {'name': 'TF1 F...","[{'iso_3166_1': 'FR', 'name': 'France'}]",13000000,4.264809e+08,/4mFsNQwbD0F237Tx7gAPotd0nbJ.jpg,movie,8.125841
40219,40220,372058,Your Name.,High schoolers Mitsuha and Taki are complete s...,2016-08-26,106.0,ja,34.461252,8.5,1030.0,<NA>,"[{'name': 'CoMix Wave Films', 'id': 10198}]","[{'iso_3166_1': 'JP', 'name': 'Japan'}]",0,3.552983e+08,/xq1Ugd62d23K2knRUx6xxuALTZB.jpg,movie,8.112548
289,290,101,Leon: The Professional,"Leon, the top hit man in New York, has earned ...",1994-09-14,110.0,fr,20.477329,8.2,4293.0,<NA>,"[{'name': 'Columbia Pictures', 'id': 5}, {'nam...","[{'iso_3166_1': 'FR', 'name': 'France'}, {'iso...",16000000,4.528497e+07,/gE8S02QUOhVnAmYu4tcrBlMTujz.jpg,movie,8.107238
3029,3030,497,The Green Mile,A supernatural tale set on death row in a Sout...,1999-12-10,189.0,en,19.966780,8.2,4166.0,<NA>,"[{'name': 'Castle Rock Entertainment', 'id': 9...","[{'iso_3166_1': 'US', 'name': 'United States o...",60000000,2.846000e+08,/3yJUlOtVa09CYJocwBU8eAryja0.jpg,movie,8.104515
1170,1171,769,GoodFellas,"The true story of Henry Hill, a half-Irish, ha...",1990-09-12,145.0,en,15.424092,8.2,3211.0,<NA>,"[{'name': 'Winkler Films', 'id': 8880}]","[{'iso_3166_1': 'US', 'name': 'United States o...",25000000,4.683639e+07,/hAPeXBdGDGmXRPj4OZZ0poH65Iu.jpg,movie,8.077464

In [19]:
get_top_movies_by_genre(
    dim_items,
    item_genres,
    "Adventure"
)

,item_id,source_item_id,title,description,release_date,runtime,language,popularity,vote_average,vote_count,belongs_to_collection,production_companies,production_countries,budget,revenue,poster_path,domain,weighted_rating
15474,15475,27205,Inception,"Cobb, a skilled thief who commits corporate es...",2010-07-14,148.0,en,29.108149,8.1,14075.0,<NA>,"[{'name': 'Legendary Pictures', 'id': 923}, {'...","[{'iso_3166_1': 'GB', 'name': 'United Kingdom'...",160000000,8.255328e+08,/qmDpIHrmpJINaRKAfWQfftjCdyi.jpg,movie,7.940302
22863,22864,157336,Interstellar,Interstellar chronicles the adventures of a gr...,2014-11-05,169.0,en,32.213481,8.1,11187.0,<NA>,"[{'name': 'Paramount Pictures', 'id': 4}, {'na...","[{'iso_3166_1': 'CA', 'name': 'Canada'}, {'iso...",165000000,6.751200e+08,/nBNZadXqJSdt05SHLqgT0HuC5Gm.jpg,movie,7.902451
1154,1155,1891,The Empire Strikes Back,"The epic saga continues as Luke Skywalker, in ...",1980-05-17,124.0,en,19.470959,8.2,5998.0,"{'id': 10, 'name': 'Star Wars Collection', 'po...","[{'name': 'Lucasfilm', 'id': 1}, {'name': 'Twe...","[{'iso_3166_1': 'US', 'name': 'United States o...",18000000,5.384000e+08,/6u1fYtxG5eqjhtCPDx04pJphQRW.jpg,movie,7.841659
6999,7000,122,The Lord of the Rings: The Return of the King,Aragorn is revealed as the heir to the ancient...,2003-12-01,201.0,en,29.324358,8.1,8226.0,"{'id': 119, 'name': 'The Lord of the Rings Col...","[{'name': 'WingNut Films', 'id': 11}, {'name':...","[{'iso_3166_1': 'NZ', 'name': 'New Zealand'}, ...",94000000,1.118889e+09,/uexxR7Kw1qYbZk0RYaF9Rx5ykbj.jpg,movie,7.839034
256,257,11,Star Wars,Princess Leia is captured and held hostage by ...,1977-05-25,121.0,en,42.149697,8.1,6778.0,"{'id': 10, 'name': 'Star Wars Collection', 'po...","[{'name': 'Lucasfilm', 'id': 1}, {'name': 'Twe...","[{'iso_3166_1': 'US', 'name': 'United States o...",11000000,7.753980e+08,/btTdmkgIvOi0FFip1sPuZI2oQG6.jpg,movie,7.790437
5480,5481,129,Spirited Away,A ten year old girl who wanders away from her ...,2001-07-20,125.0,ja,41.048867,8.3,3968.0,<NA>,"[{'name': 'Studio Ghibli', 'id': 10342}]","[{'iso_3166_1': 'JP', 'name': 'Japan'}]",15000000,2.749251e+08,/ynXoOxmDHNQ4UAy0oU6avW71HVW.jpg,movie,7.775078
4862,4863,120,The Lord of the Rings: The Fellowship of the Ring,"Young hobbit Frodo Baggins, after inheriting a...",2001-12-18,178.0,en,32.070725,8.0,8892.0,"{'id': 119, 'name': 'The Lord of the Rings Col...","[{'name': 'WingNut Films', 'id': 11}, {'name':...","[{'iso_3166_1': 'NZ', 'name': 'New Zealand'}, ...",93000000,8.713684e+08,/bxVxZb5O9OxCO0oRUNdCnpy9NST.jpg,movie,7.766697
5813,5814,121,The Lord of the Rings: The Two Towers,Frodo and Sam are trekking to Mordor to destro...,2002-12-18,179.0,en,29.423537,8.0,7641.0,"{'id': 119, 'name': 'The Lord of the Rings Col...","[{'name': 'WingNut Films', 'id': 11}, {'name':...","[{'iso_3166_1': 'NZ', 'name': 'New Zealand'}, ...",79000000,9.262874e+08,/wf3v0Pn09jnT5HSaYal7Ami3bdA.jpg,movie,7.732912
23735,23736,118340,Guardians of the Galaxy,"Light years from Earth, 26 years after being a...",2014-07-30,121.0,en,53.291601,7.9,10014.0,"{'id': 284433, 'name': 'Guardians of the Galax...","[{'name': 'Marvel Studios', 'id': 420}, {'name...","[{'iso_3166_1': 'GB', 'name': 'United Kingdom'...",170000000,7.733286e+08,/y31QB9kn3XSudA15tV7UWQ9XLuW.jpg,movie,7.699530
1225,1226,105,Back to the Future,Eighties teenager Marty McFly is accidentally ...,1985-07-03,116.0,en,25.778509,8.0,6239.0,"{'id': 264, 'name': 'Back to the Future Collec...","[{'name': 'Universal Pictures', 'id': 33}, {'n...","[{'iso_3166_1': 'US', 'name': 'United States o...",19000000,3.811098e+08,/pTpxQB1N0waaSc3OSn0e9oc8kx9.jpg,movie,7.681169
17429,17430,12445,Harry Potter and the Deathly Hallows: Part 2,"Harry, Ron and Hermione continue their quest t...",2011-07-07,130.0,en,24.990737,7.9,6141.0,"{'id': 1241, 'name': 'Harry Potter Collection'...","[{'name': 'Warner Bros.', 'id': 6194}, {'name'...","[{'iso_3166_1': 'GB', 'name': 'United Kingdom'...",125000000,1.342000e+09,/fTplI1NCSuEDP4ITLcTps739fcC.jpg,movie,7.590769
3455,3456,98,Gladiator,"In the year 180, the death of emperor Marcus A...",2000-05-01,155.0,en,23.186667,7.9,5566.0,<NA>,"[{'name': 'DreamWorks SKG', 'id': 27}, {'name'...","[{'iso_3166_1': 'GB', 'name': 'United Kingdom'...",103000000,4.576404e+08,/6WBIzCgmDCYrqh64yDREGeDk9d3.jpg,movie,7.563680
13719,13720,14160,Up,Carl Fredricksen spent his entire life dreamin...,2009-05-13,96.0,en,19.330884,7.8,7048.0,<NA>,"[{'name': 'Pixar Animation Studios', 'id': 3}]","[{'iso_3166_1': 'US', 'name': 'United States o...",175000000,7.350991e+08,/nk11pvocdb5zbFhX5oq5YiLPYMo.jpg,movie,7.538030
1167,1168,1892,Return of the Jedi,As Rebel leaders map their strategy for an all...,1983-05-23,135.0,en,14.586087,7.9,4763.0,"{'id': 10, 'name': 'Star Wars Collection', 'po...","[{'name': 'Lucasfilm', 'id': 1}, {'name': 'Twe...","[{'iso_3166_1': 'US', 'name': 'United States o...",32350000,5.727000e+08,/jx5p0aHlbPXqe3AH9G15NvmWaqQ.jpg,movie,7.516800
24437,24438,177572,Big Hero 6,The special bond that develops between plus-si...,2014-10-24,102.0,en,213.849907,7.8,6289.0,<NA>,"[{'name': 'Walt Disney Pictures', 'id': 2}, {'...","[{'iso_3166_1': 'US', 'name': 'United States o...",165000000,6.521054e+08,/9gLu47Zw5ertuFTZaxXOvNfy78T.jpg,movie,7.510743
7724,7725,673,Harry Potter and the Prisoner of Azkaban,"Harry, Ron and Hermione return to Hogwarts for...",2004-05-31,141.0,en,28.460276,7.7,6037.0,"{'id': 1241, 'name': 'Harry Potter Collection'...","[{'name': '1492 Pictures', 'id': 436}, {'name'...","[{'iso_3166_1': 'GB', 'name': 'United Kingdom'...",130000000,7.898046e+08,/jUFjMoLh8T2CWzHUSjKCojI5SHu.jpg,movie,7.414565
9695,9696,4935,Howl's Moving Castle,"When Sophie, a shy young woman, is cursed with...",2004-11-19,119.0,ja,16.136048,8.2,2049.0,<NA>,"[{'name': 'Studio Ghibli', 'id': 10342}, {'nam...","[{'iso_3166_1': 'JP', 'name': 'Japan'}]",24000000,2.347105e+08,/iMarB2ior30OAXjPa7QIdeyUfM1.jpg,movie,7.377209
2883,2884,128,Princess Mononoke,"Ashitaka, a prince of the disappearing Ainu tr...",1997-07-12,134.0,ja,17.166725,8.2,2041.0,<NA>,"[{'name': 'Miramax Films', 'id': 14}, {'name':...","[{'iso_3166_1': 'JP', 'name': 'Japan'}]",26500000,1.593753e+08,/gzlJkVfWV5VEG5xK25cvFGJgkDz.jpg,movie,7.375043
30026,30027,286217,The Martian,"During a manned mission to Mars, Astronaut Mar...",2015-09-30,141.0,en,25.629930,7.6,7442.0,<NA>,[{'name': 'Twentieth Century Fox Film Corporat...,"[{'iso_3166_1': 'US', 'name': 'United States o...",108000000,6.301619e+08,/5aGhaIHYuQbqlHWvWYqMCnj40y2.jpg,movie,7.373905
36223,36224,269149,Zootopia,"Determined to prove herself, Officer Judy Hopp...",2016-02-11,108.0,en,26.024868,7.7,4961.0,<NA>,"[{'name': 'Walt Disney Pictures', 'id': 2}, {'...","[{'iso_3166_1': 'US', 'name': 'United States o...",150000000,1.023784e+09,/sM33SANp9z6rXW8Itn7NnG1GOEs.jpg,movie,7.363023

In [20]:
get_available_genres(item_genres)

['Action',
 'Adventure',
 'Animation',
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Family',
 'Fantasy',
 'Foreign',
 'History',
 'Horror',
 'Music',
 'Mystery',
 'Romance',
 'Science Fiction',
 'TV Movie',
 'Thriller',
 'War',
 'Western']