In [1]:
from pathlib import Path
import sys
import pandas as pd
import joblib
import fastparquet

In [2]:
PROJECT_ROOT = Path.cwd().parent

sys.path.append(str(PROJECT_ROOT))

In [3]:
content_features = pd.read_parquet(f"{PROJECT_ROOT}/data/processed/movies/content_features.parquet", engine="fastparquet")

In [4]:
content_features.shape

(45430, 13)

In [ ]:
from src.recommenders.content_based import (
    search_movie,
    get_similar_movies,
    load_content_model
)

In [ ]:
vectorizer, tfidf_matrix, item_lookup = (
    load_content_model()
)

In [ ]:
from src.utils.loaders import (
    load_dim_items,
    load_content_features
)

dim_items = load_dim_items()

content_features = load_content_features()

In [5]:
from src.recommenders.content_based import (
    build_tfidf_matrix,
    build_item_lookup,
    search_movie,
    get_similar_movies
)

In [6]:
vectorizer, tfidf_matrix = build_tfidf_matrix(
    content_features
)

item_lookup = build_item_lookup(
    content_features
)

In [7]:
search_movie(
    "Toy Story",
    content_features
)

       item_id                       title
0            1                   Toy Story
2996      2997                 Toy Story 2
15342    15343                 Toy Story 3
25781    25782  Toy Story That Time Forgot
21913    21914        Toy Story of Terror!

In [8]:
search_movie(
    "The Dark Knight",
    content_features
)

       item_id                                              title
21180    21181  Batman Unmasked: The Psychology of the Dark Kn...
19782    19783            Batman: The Dark Knight Returns, Part 1
20222    20223            Batman: The Dark Knight Returns, Part 2
12477    12478                                    The Dark Knight
28680    28681                                    The Dark Knight
18244    18245                              The Dark Knight Rises

In [9]:
get_similar_movies(
    item_id=12478,
    content_features=content_features,
    tfidf_matrix=tfidf_matrix,
    item_lookup=item_lookup,
    top_n=10
)

       item_id                                    title  similarity_score
18244    18245                    The Dark Knight Rises            0.5295
10119    10120                            Batman Begins            0.4928
15505    15506               Batman: Under the Red Hood            0.4307
20222    20223  Batman: The Dark Knight Returns, Part 2            0.4079
1328      1329                           Batman Returns            0.4036
19782    19783  Batman: The Dark Knight Returns, Part 1            0.3988
9228      9229       Batman Beyond: Return of the Joker            0.3979
585        586                                   Batman            0.3945
3094      3095             Batman: Mask of the Phantasm            0.3832
150        151                           Batman Forever            0.3743

In [10]:
get_similar_movies(
    item_id=1,
    content_features=content_features,
    tfidf_matrix=tfidf_matrix,
    item_lookup=item_lookup,
    top_n=5
)

       item_id                       title  similarity_score
2996      2997                 Toy Story 2            0.5397
15342    15343                 Toy Story 3            0.5395
25781    25782  Toy Story That Time Forgot            0.3638
24505    24506                   Small Fry            0.3234
36700    36701              Toy Reanimator            0.3199

In [11]:
tfidf_matrix.shape

(45430, 20000)

In [12]:
content_features[
    [
        "title",
        "content_text"
    ]
].head()

,title,content_text
0,Toy Story,"Led by Woody, Andy's toys live happily in his ..."
1,Jumanji,When siblings Judy and Peter discover an encha...
2,Grumpier Old Men,A family wedding reignites the ancient feud be...
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom..."
4,Father of the Bride Part II,Just when George Banks has recovered from his ...

In [13]:
content_features.loc[
    content_features["title"] == "Toy Story",
    "content_text"
].iloc[0]

"Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz. But when circumstances separate Buzz and Woody from their owner, the duo eventually learns to put aside their differences. Animation Comedy Family boy boy next door friends friendship jealousy new toy rivalry toy toy comes to life John Lasseter Don Rickles Jim Varney Tim Allen Tom Hanks Wallace Shawn Toy Story Collection Pixar Animation Studios United States of America"

In [14]:
content_features["title"].duplicated().sum()

np.int64(3153)

In [15]:
content_features[
    content_features["title"] == "The Dark Knight"
]

,item_id,source_item_id,title,description,collection_name,company_names,country_names,domain,genres,keywords,directors,actors,content_text
12477,12478,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,The Dark Knight Collection,DC Comics Legendary Pictures Warner Bros. DC E...,United Kingdom United States of America,movie,Action Crime Drama Thriller,based on comic batman chaos crime fighter crim...,Christopher Nolan,Aaron Eckhart Christian Bale Gary Oldman Heath...,Batman raises the stakes in his war on crime. ...
28680,28681,72003,The Dark Knight,In a post-apocalyptic world ravaged by feuding...,,,,movie,Action Crime Drama Thriller,,Drew Maxwell,Aaron Farb Debra Lopez Kyle Walsh,In a post-apocalyptic world ravaged by feuding...

In [16]:
content_features.iloc[0]

item_id                                                            1
source_item_id                                                   862
title                                                      Toy Story
description        Led by Woody, Andy's toys live happily in his ...
collection_name                                 Toy Story Collection
company_names                                Pixar Animation Studios
country_names                               United States of America
domain                                                         movie
genres                                       Animation Comedy Family
keywords           boy boy next door friends friendship jealousy ...
directors                                              John Lasseter
actors             Don Rickles Jim Varney Tim Allen Tom Hanks Wal...
content_text       Led by Woody, Andy's toys live happily in his ...
Name: 0, dtype: object

In [ ]:
joblib.dump(
    vectorizer,
    f"{PROJECT_ROOT}/src/models/movies/tfidf_vectorizer.pkl"
)

['c:\\Users\\sm153\\OneDrive\\Documents\\Recommender  System/src/models/movies/tfidf_vectorizer.pkl']

In [19]:
joblib.dump(
    tfidf_matrix,
    f"{PROJECT_ROOT}/src/models/movies/tfidf_matrix.pkl"
)

['c:\\Users\\sm153\\OneDrive\\Documents\\Recommender  System/src/models/movies/tfidf_matrix.pkl']

In [20]:
joblib.dump(
    item_lookup,
    f"{PROJECT_ROOT}/src/models/movies/item_lookup.pkl"
)

['c:\\Users\\sm153\\OneDrive\\Documents\\Recommender  System/src/models/movies/item_lookup.pkl']