In [2]:
from pathlib import Path
import pandas as pd

In [3]:
PROJECT_ROOT = Path.cwd().parent

RAW_DATA= PROJECT_ROOT / "data" / "raw"

In [4]:
anime = pd.read_csv(
    RAW_DATA / "anime_dataset" / "anime-dataset-2023.csv"
)

anime_scores = pd.read_csv(
    RAW_DATA / "anime_dataset" / "users-score-2023.csv"
)

anime_users = pd.read_csv(
    RAW_DATA / "anime_dataset" / "users-details-2023.csv"
)

## Anime Dataset - anime-dataset-2023

In [5]:
anime.info()

<class 'pandas.DataFrame'>
RangeIndex: 24905 entries, 0 to 24904
Data columns (total 24 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   anime_id      24905 non-null  int64
 1   Name          24905 non-null  str
 2   English name  24905 non-null  str
 3   Other name    24905 non-null  str
 4   Score         24905 non-null  str
 5   Genres        24905 non-null  str
 6   Synopsis      24905 non-null  str
 7   Type          24905 non-null  str
 8   Episodes      24905 non-null  str
 9   Aired         24905 non-null  str
 10  Premiered     24905 non-null  str
 11  Status        24905 non-null  str
 12  Producers     24905 non-null  str
 13  Licensors     24905 non-null  str
 14  Studios       24905 non-null  str
 15  Source        24905 non-null  str
 16  Duration      24905 non-null  str
 17  Rating        24905 non-null  str
 18  Rank          24905 non-null  str
 19  Popularity    24905 non-null  int64
 20  Favorites     24905 non-null  int64
 21  Scored By     24905 non-null  str
 22  Members       24905 non-null  int64
 23  Image URL     24905 non-null  str
dtypes: int64(4), str(20)
memory usage: 4.6 MB

In [6]:
anime.head()

,anime_id,Name,English name,Other name,Score,Genres,Synopsis,Type,Episodes,Aired,...,Studios,Source,Duration,Rating,Rank,Popularity,Favorites,Scored By,Members,Image URL
0,1,Cowboy Bebop,Cowboy Bebop,カウボーイビバップ,8.75,"Action, Award Winning, Sci-Fi","Crime is timeless. By the year 2071, humanity ...",TV,26.0,"Apr 3, 1998 to Apr 24, 1999",...,Sunrise,Original,24 min per ep,R - 17+ (violence & profanity),41.0,43,78525,914193.0,1771505,https://cdn.myanimelist.net/images/anime/4/196...
1,5,Cowboy Bebop: Tengoku no Tobira,Cowboy Bebop: The Movie,カウボーイビバップ 天国の扉,8.38,"Action, Sci-Fi","Another day, another bounty—such is the life o...",Movie,1.0,"Sep 1, 2001",...,Bones,Original,1 hr 55 min,R - 17+ (violence & profanity),189.0,602,1448,206248.0,360978,https://cdn.myanimelist.net/images/anime/1439/...
2,6,Trigun,Trigun,トライガン,8.22,"Action, Adventure, Sci-Fi","Vash the Stampede is the man with a $$60,000,0...",TV,26.0,"Apr 1, 1998 to Sep 30, 1998",...,Madhouse,Manga,24 min per ep,PG-13 - Teens 13 or older,328.0,246,15035,356739.0,727252,https://cdn.myanimelist.net/images/anime/7/203...
3,7,Witch Hunter Robin,Witch Hunter Robin,Witch Hunter ROBIN (ウイッチハンターロビン),7.25,"Action, Drama, Mystery, Supernatural",Robin Sena is a powerful craft user drafted in...,TV,26.0,"Jul 3, 2002 to Dec 25, 2002",...,Sunrise,Original,25 min per ep,PG-13 - Teens 13 or older,2764.0,1795,613,42829.0,111931,https://cdn.myanimelist.net/images/anime/10/19...
4,8,Bouken Ou Beet,Beet the Vandel Buster,冒険王ビィト,6.94,"Adventure, Fantasy, Supernatural",It is the dark century and the people are suff...,TV,52.0,"Sep 30, 2004 to Sep 29, 2005",...,Toei Animation,Manga,23 min per ep,PG - Children,4240.0,5126,14,6413.0,15001,https://cdn.myanimelist.net/images/anime/7/215...

In [7]:
anime["anime_id"].nunique()

24905

In [10]:
anime[["Score", "Rank", "Scored By", "Episodes"]].sample(10)

         Score     Rank Scored By Episodes
18940     5.05  11863.0     110.0      1.0
22785  UNKNOWN  UNKNOWN   UNKNOWN      1.0
2381      6.87   4510.0   16037.0     13.0
126       6.56   6039.0    2671.0     12.0
3326      5.68  10142.0     480.0      8.0
12410     8.32    227.0   19812.0      2.0
23498  UNKNOWN  UNKNOWN   UNKNOWN      1.0
18282  UNKNOWN  17653.0   UNKNOWN      1.0
20796  UNKNOWN  19478.0   UNKNOWN     26.0
11971     6.57   5969.0    2020.0      1.0

In [21]:
anime["Score"].value_counts().head(10)

Score
UNKNOWN    9213
6.31         80
6.54         80
6.51         79
6.25         79
6.52         78
6.5          76
6.36         75
6.32         74
5.99         74
Name: count, dtype: int64

In [12]:
pd.to_numeric(anime["Score"], errors="coerce").isna().sum()

np.int64(9213)

In [27]:
mask_score = pd.to_numeric(anime["Score"], errors="coerce").isna()

anime.loc[mask_score, "Score"].value_counts()

Score
UNKNOWN    9213
Name: count, dtype: int64

In [20]:
anime["Episodes"].value_counts().head(10)

Episodes
1.0        11532
12.0        1919
2.0         1528
26.0        1201
13.0         984
52.0         812
3.0          712
UNKNOWN      611
4.0          553
6.0          416
Name: count, dtype: int64

In [16]:
pd.to_numeric(anime["Episodes"], errors="coerce").isna().sum()

np.int64(611)

In [28]:
mask_episodes = pd.to_numeric(anime["Episodes"], errors="coerce").isna()

anime.loc[mask_episodes, "Episodes"].value_counts()

Episodes
UNKNOWN    611
Name: count, dtype: int64

In [22]:
anime["Rank"].value_counts().head(10)

Rank
UNKNOWN    4612
0.0         187
7175.0        4
9618.0        4
6491.0        4
12591.0       4
6442.0        4
12881.0       4
10515.0       4
7747.0        4
Name: count, dtype: int64

In [17]:
pd.to_numeric(anime["Rank"], errors="coerce").isna().sum()

np.int64(4612)

In [29]:
mask_rank = pd.to_numeric(anime["Rank"], errors="coerce").isna()

anime.loc[mask_rank, "Rank"].value_counts()

Rank
UNKNOWN    4612
Name: count, dtype: int64

In [24]:
anime["Scored By"].value_counts().head(10)

Scored By
UNKNOWN    9213
121.0        35
128.0        35
150.0        33
172.0        33
130.0        32
134.0        31
152.0        31
123.0        30
124.0        30
Name: count, dtype: int64

In [18]:
pd.to_numeric(anime["Scored By"], errors="coerce").isna().sum()

np.int64(9213)

In [30]:
mask_scored_by = pd.to_numeric(anime["Scored By"], errors="coerce").isna()

anime.loc[mask_scored_by, "Scored By"].value_counts()

Scored By
UNKNOWN    9213
Name: count, dtype: int64

In [34]:
anime[anime["Rank"] == "0.0"][
    ["anime_id","Name","Score","Rank","Scored By"]
].sample(10)

       anime_id                            Name    Score Rank Scored By
24397     55081        Tsukuyo no Nakama Atsume  UNKNOWN  0.0   UNKNOWN
23200     53053                  Genshin Impact  UNKNOWN  0.0   UNKNOWN
24613     55380                      SLoWMoTIoN  UNKNOWN  0.0   UNKNOWN
22033     50995  Zenryoku Usagi (Anime Project)  UNKNOWN  0.0   UNKNOWN
24498     55227                    Night Flower  UNKNOWN  0.0   UNKNOWN
24633     55401               Kakkoyoku Naritai  UNKNOWN  0.0   UNKNOWN
24390     55072              Kay-chan no Enikki  UNKNOWN  0.0   UNKNOWN
24620     55387         Kuusou Shou mo Nai Hibi  UNKNOWN  0.0   UNKNOWN
24904     55735                  Shijuuku Nichi  UNKNOWN  0.0   UNKNOWN
22338     51521        Xian Jian Qi Xia Zhuan 4  UNKNOWN  0.0   UNKNOWN

In [35]:
anime[anime["Rank"] == "0.0"][
    ["Score", "Scored By"]
].value_counts()

Score    Scored By
UNKNOWN  UNKNOWN      187
Name: count, dtype: int64

## Anime Dataset - users-details-2023

In [37]:
anime_users.info()

<class 'pandas.DataFrame'>
RangeIndex: 731290 entries, 0 to 731289
Data columns (total 16 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Mal ID            731290 non-null  int64
 1   Username          731289 non-null  str
 2   Gender            224383 non-null  str
 3   Birthday          168068 non-null  str
 4   Location          152805 non-null  str
 5   Joined            731290 non-null  str
 6   Days Watched      731282 non-null  float64
 7   Mean Score        731282 non-null  float64
 8   Watching          731282 non-null  float64
 9   Completed         731282 non-null  float64
 10  On Hold           731282 non-null  float64
 11  Dropped           731282 non-null  float64
 12  Plan to Watch     731282 non-null  float64
 13  Total Entries     731282 non-null  float64
 14  Rewatched         731282 non-null  float64
 15  Episodes Watched  731282 non-null  float64
dtypes: float64(10), int64(1), str(5)
memory usage: 89.3 MB

In [38]:
anime_users.head()

,Mal ID,Username,Gender,Birthday,Location,Joined,Days Watched,Mean Score,Watching,Completed,On Hold,Dropped,Plan to Watch,Total Entries,Rewatched,Episodes Watched
0,1,Xinil,Male,1985-03-04T00:00:00+00:00,California,2004-11-05T00:00:00+00:00,142.3,7.37,1.0,233.0,8.0,93.0,64.0,399.0,60.0,8458.0
1,3,Aokaado,Male,NaN,"Oslo, Norway",2004-11-11T00:00:00+00:00,68.6,7.34,23.0,137.0,99.0,44.0,40.0,343.0,15.0,4072.0
2,4,Crystal,Female,NaN,"Melbourne, Australia",2004-11-13T00:00:00+00:00,212.8,6.68,16.0,636.0,303.0,0.0,45.0,1000.0,10.0,12781.0
3,9,Arcane,NaN,NaN,NaN,2004-12-05T00:00:00+00:00,30.0,7.71,5.0,54.0,4.0,3.0,0.0,66.0,0.0,1817.0
4,18,Mad,NaN,NaN,NaN,2005-01-03T00:00:00+00:00,52.0,6.27,1.0,114.0,10.0,5.0,23.0,153.0,42.0,3038.0

In [39]:
anime_users["Mal ID"].nunique()

731290

In [40]:
anime_users.isnull().sum().sort_values(ascending=False)

Location            578485
Birthday            563222
Gender              506907
Days Watched             8
Mean Score               8
On Hold                  8
Completed                8
Watching                 8
Plan to Watch            8
Total Entries            8
Rewatched                8
Dropped                  8
Episodes Watched         8
Username                 1
Joined                   0
Mal ID                   0
dtype: int64

In [41]:
anime_users[anime_users["Username"].isna()]

,Mal ID,Username,Gender,Birthday,Location,Joined,Days Watched,Mean Score,Watching,Completed,On Hold,Dropped,Plan to Watch,Total Entries,Rewatched,Episodes Watched
19618,20930,NaN,NaN,NaN,NaN,2007-11-09T00:00:00+00:00,58.8,7.59,8.0,236.0,8.0,3.0,17.0,272.0,14.0,3447.0

In [42]:
anime_users[
    anime_users["Days Watched"].isna()
]

,Mal ID,Username,Gender,Birthday,Location,Joined,Days Watched,Mean Score,Watching,Completed,On Hold,Dropped,Plan to Watch,Total Entries,Rewatched,Episodes Watched
7532,8682,DeleteMe3409,Female,NaN,NaN,2007-07-27T00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74352,79090,rosycrystals,Female,1993-11-29T00:00:00+00:00,Kansas,2008-07-23T00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
120266,125668,BlazingDevil,Male,1995-07-07T00:00:00+00:00,Kamloops British Columbia in Canada,2008-12-20T00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
147943,160113,FuckedUpProfile,Female,1993-06-19T00:00:00+00:00,Organisation 13,2009-03-17T00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196115,231825,Account_Closed,Female,1994-04-22T00:00:00+00:00,"Portersville, Pennsylvania",2009-09-08T00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196899,232646,-Lovely-,Female,1994-04-22T00:00:00+00:00,"Portersville,Pennsylvania",2009-09-10T00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
233070,277237,sarah_sweet,Female,1997-08-14T00:00:00+00:00,Romania,2010-01-02T00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
470599,561555,RaisinMuffins,Male,NaN,NaN,2011-08-31T00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Anime Dataset - users-score-2023

In [48]:
anime_scores.info(show_counts=True)

<class 'pandas.DataFrame'>
RangeIndex: 24325191 entries, 0 to 24325190
Data columns (total 5 columns):
 #   Column       Non-Null Count     Dtype
---  ------       --------------     -----
 0   user_id      24325191 non-null  int64
 1   Username     24324959 non-null  str
 2   anime_id     24325191 non-null  int64
 3   Anime Title  24325191 non-null  str
 4   rating       24325191 non-null  int64
dtypes: int64(3), str(2)
memory usage: 927.9 MB

In [45]:
anime_scores.head()

   user_id Username  anime_id             Anime Title  rating
0        1    Xinil        21               One Piece       9
1        1    Xinil        48             .hack//Sign       7
2        1    Xinil       320                  A Kite       5
3        1    Xinil        49        Aa! Megami-sama!       8
4        1    Xinil       304  Aa! Megami-sama! Movie       8

In [49]:
anime_scores[["user_id", "anime_id"]].duplicated().sum()

np.int64(0)

In [52]:
anime_scores[anime_scores["Username"].isna()].sample(10)

,user_id,Username,anime_id,Anime Title,rating
1571911,20930,NaN,1033,Sennen Joyuu,8
1571735,20930,NaN,150,Blood+,7
1571802,20930,NaN,26055,JoJo no Kimyou na Bouken Part 3: Stardust Crus...,7
1571877,20930,NaN,34475,Monster Strike: Rain of Memories,7
1571743,20930,NaN,1818,Claymore,9
1571925,20930,NaN,849,Suzumiya Haruhi no Yuuutsu,9
1571832,20930,NaN,87,Kidou Senshi Gundam: Gyakushuu no Char,6
1571818,20930,NaN,82,Kidou Senshi Gundam 0080: Pocket no Naka no Se...,7
1571933,20930,NaN,1303,The Animatrix,7
1571784,20930,NaN,37141,Hataraku Saibou,8

In [55]:
anime_scores[anime_scores["Username"].isna()]["user_id"].nunique()

1

In [56]:
anime_scores["rating"].value_counts().sort_index()

rating
1       98069
2      132092
3      233675
4      562822
5     1379480
6     2766482
7     5452152
8     6060484
9     4429914
10    3210021
Name: count, dtype: int64