In [1]:
from pathlib import Path
import pandas as pd

In [2]:
PROJECT_ROOT = Path.cwd().parent

RAW_DATA= PROJECT_ROOT / "data" / "raw"

In [3]:
movies_metadata = pd.read_csv(
    RAW_DATA / "movies_dataset" / "movies_metadata.csv",
    low_memory=False
)

credits = pd.read_csv(
    RAW_DATA / "movies_dataset" / "credits.csv"
)

keywords = pd.read_csv(
    RAW_DATA / "movies_dataset" / "keywords.csv"
)

links = pd.read_csv(
    RAW_DATA / "movies_dataset" / "links.csv"
)

ratings = pd.read_csv(
    RAW_DATA / "movies_dataset" / "ratings.csv"
)

## Movies Dataset - movies_metadata

In [4]:
movies_metadata.info()

<class 'pandas.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  str
 1   belongs_to_collection  4494 non-null   str
 2   budget                 45466 non-null  str
 3   genres                 45466 non-null  str
 4   homepage               7782 non-null   str
 5   id                     45466 non-null  str
 6   imdb_id                45449 non-null  str
 7   original_language      45455 non-null  str
 8   original_title         45466 non-null  str
 9   overview               44512 non-null  str
 10  popularity             45461 non-null  str
 11  poster_path            45080 non-null  str
 12  production_companies   45463 non-null  str
 13  production_countries   45463 non-null  str
 14  release_date           45379 non-null  str
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  str
 18  status                 45379 non-null  str
 19  tagline                20412 non-null  str
 20  title                  45460 non-null  str
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(1), str(19)
memory usage: 39.1+ MB

In [7]:
movies_metadata["title"].nunique()

42277

In [10]:
movies_metadata[movies_metadata["title"].duplicated(keep=False)]

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
5,False,NaN,60000000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",NaN,949,tt0113277,en,Heat,"Obsessive master thief, Neil McCauley leads a ...",...,1995-12-15,187436818.0,170.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,A Los Angeles Crime Saga,Heat,False,7.7,1886.0
6,False,NaN,58000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",NaN,11860,tt0114319,en,Sabrina,An ugly duckling having undergone a remarkable...,...,1995-12-15,0.0,127.0,"[{'iso_639_1': 'fr', 'name': 'Français'}, {'is...",Released,You are cordially invited to the most surprisi...,Sabrina,False,6.2,141.0
16,False,NaN,16500000,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,4584,tt0114388,en,Sense and Sensibility,"Rich Mr. Dashwood dies, leaving his second wif...",...,1995-12-13,135000000.0,136.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Lose your heart and come to your senses.,Sense and Sensibility,False,7.2,364.0
25,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,16420,tt0114057,en,Othello,The evil Iago pretends to be friend of Othello...,...,1995-12-15,0.0,123.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"Envy, greed, jealousy and love.",Othello,False,7.0,33.0
27,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,17015,tt0114117,en,Persuasion,This film adaptation of Jane Austen's last nov...,...,1995-09-27,0.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Persuasion,False,7.4,36.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45421,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10769, 'n...",NaN,52103,tt0144020,zh,Xiao Wu,Little pocket thief Wu never got away from the...,...,1997-01-01,0.0,105.0,"[{'iso_639_1': 'zh', 'name': '普通话'}]",Released,NaN,Pickpocket,False,7.2,13.0
45453,False,NaN,0,"[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...",NaN,404604,tt5690142,hi,Maa,The bliss of a biology teacher’s family life i...,...,2017-07-07,0.0,146.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,Mom,False,6.6,14.0
45454,False,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,420346,tt4130180,en,The Morning After,The Morning After is a feature film that consi...,...,2015-01-11,0.0,79.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,What happened last night?,The Morning After,False,4.0,2.0
45460,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...",NaN,30840,tt0102797,en,Robin Hood,"Yet another version of the classic epic, with ...",...,1991-05-13,0.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Robin Hood,False,5.7,26.0
45463,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",NaN,67758,tt0303758,en,Betrayal,"When one of her hits goes wrong, a professiona...",...,2003-08-01,0.0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A deadly game of wits.,Betrayal,False,3.8,6.0

In [5]:
movies_metadata[[
    "id",
    "title",
    "genres",
    "overview",
    "vote_average",
    "vote_count",
    "release_date",
    "original_language"
]].head()

,id,title,genres,overview,vote_average,vote_count,release_date,original_language
0,862,Toy Story,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...","Led by Woody, Andy's toys live happily in his ...",7.7,5415.0,1995-10-30,en
1,8844,Jumanji,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",When siblings Judy and Peter discover an encha...,6.9,2413.0,1995-12-15,en
2,15602,Grumpier Old Men,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",A family wedding reignites the ancient feud be...,6.5,92.0,1995-12-22,en
3,31357,Waiting to Exhale,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...","Cheated on, mistreated and stepped on, the wom...",6.1,34.0,1995-12-22,en
4,11862,Father of the Bride Part II,"[{'id': 35, 'name': 'Comedy'}]",Just when George Banks has recovered from his ...,5.7,173.0,1995-02-10,en

In [6]:
movies_metadata["id"].nunique()

45436

In [7]:
modeling_cols = [
    "id",
    "title",
    "genres",
    "overview",
    "vote_average",
    "vote_count",
    "release_date",
    "original_language"
]

movies_metadata[modeling_cols].isnull().sum()

id                     0
title                  6
genres                 0
overview             954
vote_average           6
vote_count             6
release_date          87
original_language     11
dtype: int64

In [8]:
movies_metadata[movies_metadata["title"].isna()][
    ["id","title","overview"]
].head(10)

               id title                                           overview
19729       82663   NaN  British soldiers force a recently captured IRA...
19730  1997-08-20   NaN                                           Released
29502      122662   NaN         Third film of the Mardock Scramble series.
29503  2012-09-29   NaN                                           Released
35586      249260   NaN  A group of skiers are terrorized during spring...
35587  2014-01-01   NaN                                           Released

In [9]:
movies_metadata[movies_metadata["overview"].isna()][
    ["id","title","overview"]
].head(10)

         id                           title overview
32    78802                Wings of Courage      NaN
300  161495                       Roommates      NaN
634  287305  Peanuts – Die Bank zahlt alles      NaN
635  339428                   Happy Weekend      NaN
641   10801                   The Superwife      NaN
644  278978       Und keiner weint mir nach      NaN
679  117730            Under The Domim Tree      NaN
792  281085               A Boy Called Hate      NaN
802  282919                       Diebinnen      NaN
821   48144     The Day the Sun Turned Cold      NaN

In [10]:
movies_metadata[movies_metadata["release_date"].isna()][
    ["id","title","release_date"]
].head(10)

           id                                    title release_date
711    365371     War Stories Our Mother Never Told Us          NaN
734    215107                    Vermont Is for Lovers          NaN
3460    94214               Jails, Hospitals & Hip-Hop          NaN
3628   207731                           Boricua's Bond          NaN
5879    99885                      Divine Intervention          NaN
13839   91205                     Bling: A Planet Rock          NaN
14801  281287    Dead Ahead: The Exxon Valdez Disaster          NaN
16836  442417  Das Experiment 770 - Gebären auf Befehl          NaN
16953  367647                              Connections          NaN
17339  366044                            Human Failure          NaN

In [11]:
movies_metadata[movies_metadata["original_language"].isna()][
    ["id","title","original_language"]
].head(10)

           id                       title original_language
19574  283101     Shadowing the Third Man               NaN
21602  103902              Unfinished Sky               NaN
22832  359195             13 Fighting Men               NaN
32141  147050                   Lambchops               NaN
37407  257095               Prince Bayaya               NaN
41047  332742              Song of Lahore               NaN
41872  144410  Annabelle Serpentine Dance               NaN
44057  380438       Lettre d'une inconnue               NaN
44410  381096                        Yarn               NaN
44576  381525                      WiNWiN               NaN

In [12]:
movies_metadata[movies_metadata["vote_average"].isna()][
    ["id","title","vote_average"]
].head(10)

               id title  vote_average
19729       82663   NaN           NaN
19730  1997-08-20   NaN           NaN
29502      122662   NaN           NaN
29503  2012-09-29   NaN           NaN
35586      249260   NaN           NaN
35587  2014-01-01   NaN           NaN

In [13]:
movies_metadata[movies_metadata["vote_count"].isna()][
    ["id","title","vote_count"]
].head(10)

               id title  vote_count
19729       82663   NaN         NaN
19730  1997-08-20   NaN         NaN
29502      122662   NaN         NaN
29503  2012-09-29   NaN         NaN
35586      249260   NaN         NaN
35587  2014-01-01   NaN         NaN

In [14]:
movies_metadata["id"].str.isnumeric().value_counts()

id
True     45463
False        3
Name: count, dtype: int64

In [15]:
mm_duplicates = movies_metadata[
    movies_metadata["id"].duplicated(keep=False)
]

mm_duplicates.shape

(59, 24)

In [16]:
mm_duplicates[["id","title", "genres", "overview", "release_date", "vote_average", "vote_count", "original_language"]].sort_values("id").head(10)

,id,title,genres,overview,release_date,vote_average,vote_count,original_language
676,105045,The Promise,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...","East-Berlin, 1961, shortly after the erection ...",1995-02-16,5.0,1.0,de
1465,105045,The Promise,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...","East-Berlin, 1961, shortly after the erection ...",1995-02-16,5.0,1.0,de
44821,10991,Pokémon: Spell of the Unknown,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",When Molly Hale's sadness of her father's disa...,2000-07-08,6.0,144.0,ja
4114,10991,Pokémon: Spell of the Unknown,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",When Molly Hale's sadness of her father's disa...,2000-07-08,6.0,143.0,ja
5710,109962,Rich and Famous,"[{'id': 18, 'name': 'Drama'}]",Two literary women compete for 20 years: one w...,1981-09-23,4.9,7.0,en
20899,109962,Rich and Famous,"[{'id': 18, 'name': 'Drama'}]",Two literary women compete for 20 years: one w...,1981-09-23,4.9,7.0,en
23534,110428,Camille Claudel 1915,"[{'id': 18, 'name': 'Drama'}]","Winter, 1915. Confined by her family to an asy...",2013-03-13,7.0,20.0,fr
4356,110428,Camille Claudel 1915,"[{'id': 18, 'name': 'Drama'}]","Winter, 1915. Confined by her family to an asy...",2013-03-13,7.0,20.0,fr
24844,11115,Deal,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",As an ex-gambler teaches a hot-shot college ki...,2008-01-29,5.2,22.0,en
14012,11115,Deal,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",As an ex-gambler teaches a hot-shot college ki...,2008-01-29,5.2,22.0,en

## Movies Dataset - credits

In [17]:
credits.info()

<class 'pandas.DataFrame'>
RangeIndex: 45476 entries, 0 to 45475
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   cast    45476 non-null  str
 1   crew    45476 non-null  str
 2   id      45476 non-null  int64
dtypes: int64(1), str(2)
memory usage: 1.0 MB

In [18]:
credits.head()

,cast,crew,id
0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",862
1,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",8844
2,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",15602
3,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",31357
4,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",11862

In [19]:
credits["id"].nunique()

45432

In [20]:
credits[credits["id"].duplicated(keep=False)].sort_values("id").head(10)

,cast,crew,id
25950,"[{'cast_id': 12, 'character': 'The Creature', ...","[{'credit_id': '52fe4380c3a36847f80590dd', 'de...",3057
25885,"[{'cast_id': 12, 'character': 'The Creature', ...","[{'credit_id': '52fe4380c3a36847f80590dd', 'de...",3057
5865,"[{'cast_id': 15, 'character': 'Chuck Barris', ...","[{'credit_id': '52fe43e2c3a36847f80760b5', 'de...",4912
33838,"[{'cast_id': 15, 'character': 'Chuck Barris', ...","[{'credit_id': '52fe43e2c3a36847f80760a9', 'de...",4912
9165,"[{'cast_id': 11, 'character': 'Jef Costello', ...","[{'credit_id': '52fe440ac3a36847f807ee01', 'de...",5511
7345,"[{'cast_id': 11, 'character': 'Jef Costello', ...","[{'credit_id': '52fe440ac3a36847f807ee01', 'de...",5511
25969,"[{'cast_id': 11, 'character': 'Mike Gaucher / ...","[{'credit_id': '52fe44b8c3a36847f80a6389', 'de...",8767
25895,"[{'cast_id': 11, 'character': 'Mike Gaucher / ...","[{'credit_id': '52fe44b8c3a36847f80a6389', 'de...",8767
25893,"[{'cast_id': 1, 'character': 'Churchill', 'cre...","[{'credit_id': '52fe4527c3a36847f80bf5e5', 'de...",9755
25967,"[{'cast_id': 1, 'character': 'Churchill', 'cre...","[{'credit_id': '52fe4527c3a36847f80bf5e5', 'de...",9755

## Movies Dataset - keywords

In [21]:
keywords.info()

<class 'pandas.DataFrame'>
RangeIndex: 46419 entries, 0 to 46418
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        46419 non-null  int64
 1   keywords  46419 non-null  str
dtypes: int64(1), str(1)
memory usage: 725.4 KB

In [22]:
keywords.head()

      id                                           keywords
0    862  [{'id': 931, 'name': 'jealousy'}, {'id': 4290,...
1   8844  [{'id': 10090, 'name': 'board game'}, {'id': 1...
2  15602  [{'id': 1495, 'name': 'fishing'}, {'id': 12392...
3  31357  [{'id': 818, 'name': 'based on novel'}, {'id':...
4  11862  [{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n...

In [23]:
keywords["id"].nunique()

45432

In [24]:
keywords[keywords["id"].duplicated(keep=False)].sort_values("id").head(10)

         id                                           keywords
37095  1998  [{'id': 417, 'name': 'corruption'}, {'id': 612...
36138  1998  [{'id': 417, 'name': 'corruption'}, {'id': 612...
36822  3025  [{'id': 212, 'name': 'london england'}, {'id':...
35865  3025  [{'id': 212, 'name': 'london england'}, {'id':...
35999  3692  [{'id': 470, 'name': 'spy'}, {'id': 591, 'name...
36956  3692  [{'id': 470, 'name': 'spy'}, {'id': 591, 'name...
35674  4459  [{'id': 1233, 'name': 'composer'}, {'id': 3423...
36631  4459  [{'id': 1233, 'name': 'composer'}, {'id': 3423...
36894  4709                                                 []
35937  4709                                                 []

## Movies Dataset - links

In [25]:
links.info()

<class 'pandas.DataFrame'>
RangeIndex: 45843 entries, 0 to 45842
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  45843 non-null  int64
 1   imdbId   45843 non-null  int64
 2   tmdbId   45624 non-null  float64
dtypes: float64(1), int64(2)
memory usage: 1.0 MB

In [26]:
links.head()

   movieId  imdbId   tmdbId
0        1  114709    862.0
1        2  113497   8844.0
2        3  113228  15602.0
3        4  114885  31357.0
4        5  113041  11862.0

In [27]:
links["movieId"].nunique()

45843

In [28]:
links["tmdbId"].nunique()

45594

In [29]:
links[links["tmdbId"].isna()].sample(10)

       movieId   imdbId  tmdbId
23365   110293  1606674     NaN
5469      5565   309521     NaN
22489   107252   401019     NaN
18112    90432   222581     NaN
20299    99420  1634016     NaN
20677   100655  1337601     NaN
23820   112163  2670642     NaN
6844      6955   169624     NaN
757        770    38426     NaN
23036   109193    46058     NaN

In [31]:
links[links["tmdbId"].duplicated(keep=False)].sort_values("tmdbId").head(10)

       movieId  imdbId   tmdbId
5905      6003  290538   4912.0
34144   144606  270288   4912.0
9215     27136  165303   5511.0
7388      7587   62229   5511.0
45197   174533  235679  10991.0
4148      4241  266860  10991.0
14089    70545  848281  11115.0
25138   116752  446676  11115.0
45202   174543  287635  12600.0
5574      5672  313487  12600.0