In [1]:
from pathlib import Path
import pandas as pd

In [2]:
PROJECT_ROOT = Path.cwd().parent

RAW_DATA= PROJECT_ROOT / "data" / "raw"

In [3]:
tvshows = pd.read_csv(
    RAW_DATA / "tvshows_dataset" / "TMDB_tv_dataset_v3.csv"
)

## TVShows Dataset - TMDB_tv_dataset_v3

In [4]:
tvshows.info()

<class 'pandas.DataFrame'>
RangeIndex: 168639 entries, 0 to 168638
Data columns (total 29 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   id                    168639 non-null  int64
 1   name                  168634 non-null  str
 2   number_of_seasons     168639 non-null  int64
 3   number_of_episodes    168639 non-null  int64
 4   original_language     168639 non-null  str
 5   vote_count            168639 non-null  int64
 6   vote_average          168639 non-null  float64
 7   overview              93333 non-null   str
 8   adult                 168639 non-null  bool
 9   backdrop_path         77780 non-null   str
 10  first_air_date        136903 non-null  str
 11  last_air_date         138735 non-null  str
 12  homepage              50998 non-null   str
 13  in_production         168639 non-null  bool
 14  original_name         168634 non-null  str
 15  popularity            168639 non-null  float64
 16  poster_path           108737 non-null  str
 17  type                  168639 non-null  str
 18  status                168639 non-null  str
 19  tagline               5330 non-null    str
 20  genres                99713 non-null   str
 21  created_by            36496 non-null   str
 22  languages             110050 non-null  str
 23  networks              97589 non-null   str
 24  origin_country        137609 non-null  str
 25  spoken_languages      109280 non-null  str
 26  production_companies  59342 non-null   str
 27  production_countries  77511 non-null   str
 28  episode_run_time      168639 non-null  int64
dtypes: bool(2), float64(2), int64(5), str(20)
memory usage: 35.1 MB

In [5]:
tvshows.head()

,id,name,number_of_seasons,number_of_episodes,original_language,vote_count,vote_average,overview,adult,backdrop_path,...,tagline,genres,created_by,languages,networks,origin_country,spoken_languages,production_companies,production_countries,episode_run_time
0,1399,Game of Thrones,8,73,en,21857,8.442,Seven noble families fight for control of the ...,False,/2OMB0ynKlyIenMJWI2Dy9IWT4c.jpg,...,Winter Is Coming,"Sci-Fi & Fantasy, Drama, Action & Adventure","David Benioff, D.B. Weiss",en,HBO,US,English,"Revolution Sun Studios, Television 360, Genera...","United Kingdom, United States of America",0
1,71446,Money Heist,3,41,es,17836,8.257,"To carry out the biggest heist in history, a m...",False,/gFZriCkpJYsApPZEF3jhxL4yLzG.jpg,...,The perfect robbery.,"Crime, Drama",Álex Pina,es,"Netflix, Antena 3",ES,Español,Vancouver Media,Spain,70
2,66732,Stranger Things,4,34,en,16161,8.624,"When a young boy vanishes, a small town uncove...",False,/2MaumbgBlW1NoPo3ZJO38A6v7OS.jpg,...,Every ending has a beginning.,"Drama, Sci-Fi & Fantasy, Mystery","Matt Duffer, Ross Duffer",en,Netflix,US,English,"21 Laps Entertainment, Monkey Massacre Product...",United States of America,0
3,1402,The Walking Dead,11,177,en,15432,8.121,Sheriff's deputy Rick Grimes awakens from a co...,False,/x4salpjB11umlUOltfNvSSrjSXm.jpg,...,Fight the dead. Fear the living.,"Action & Adventure, Drama, Sci-Fi & Fantasy",Frank Darabont,en,AMC,US,English,"AMC Studios, Circle of Confusion, Valhalla Mot...",United States of America,42
4,63174,Lucifer,6,93,en,13870,8.486,"Bored and unhappy as the Lord of Hell, Lucifer...",False,/aDBRtunw49UF4XmqfyNuD9nlYIu.jpg,...,It's good to be bad.,"Crime, Sci-Fi & Fantasy",Tom Kapinos,en,"FOX, Netflix",US,English,"Warner Bros. Television, DC Entertainment, Jer...",United States of America,45

In [6]:
tvshows["id"].nunique()

164705

In [9]:
tvshows[tvshows["id"].duplicated(keep=False)] \
    .sort_values("id") \
    [["id","name","number_of_seasons","vote_average"]].head(10)

            id                          name  number_of_seasons  vote_average
97167   237050             Archives secrètes                  1           0.0
164937  237050             Archives secrètes                  1           0.0
164938  237051  Sefure no Hinkaku The Series                  1           0.0
97238   237051  Sefure no Hinkaku The Series                  1           0.0
97152   237052                 Les Disparues                  1           0.0
164947  237052                 Les Disparues                  1           0.0
164940  237053           KEY is Good & Great                  1           0.0
88129   237053           KEY is Good & Great                  1           0.0
97110   237054             Sådan er det bare                  1           0.0
164942  237054             Sådan er det bare                  1           0.0

In [11]:
tvshows_duplicates = tvshows[tvshows["id"].duplicated(keep=False)]

tvshows_duplicates.groupby("id").size().value_counts()

3    882
2    547
4    541
Name: count, dtype: int64

In [12]:
tvshows[tvshows["id"] == 237050].T

,97167,164937
id,237050,237050
name,Archives secrètes,Archives secrètes
number_of_seasons,1,1
number_of_episodes,5,5
original_language,fr,fr
vote_count,0,0
vote_average,0.0,0.0
overview,NaN,NaN
adult,False,False
backdrop_path,/64235X8vuIZT3Up0eI6hUfyAWZe.jpg,/64235X8vuIZT3Up0eI6hUfyAWZe.jpg
first_air_date,2021-09-09,2021-09-09
last_air_date,2023-10-09,2023-09-15
homepage,NaN,https://www.france.tv/france-3/archives-secret...
in_production,True,True
original_name,Archives secrètes,Archives secrètes
popularity,3.255,1.545
poster_path,NaN,/fpeNTDTz4geJ3gmfdzFbx5hlgC2.jpg
type,Documentary,Documentary
status,Returning Series,Returning Series
tagline,NaN,NaN
genres,NaN,Documentary
created_by,NaN,NaN
languages,fr,fr
networks,NaN,NaN
origin_country,FR,FR
spoken_languages,Français,Français
production_companies,NaN,"Magnéto Presse, La Bambola, France Télévisions"
production_countries,NaN,NaN
episode_run_time,0,0